spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/postgres
    username: postgres
    password: postgres
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
module:
  auth:
    service-url: http://localhost:8082
server:
  port: 8085
logging:
  level:
    org.springframework.security: TRACE
    oi.github.resilience4j: DEBUG
resilience4j:
  ratelimiter:
    instances:
      jwtRateLimiter:
        limitForPeriod: 5000
        limitRefreshPeriod: 1s
        timeoutDuration: 2s # Не ждать при превышении лимита
  retry:
    instances:
      jwtRetry:
        maxAttempts: 3
        waitDuration: 5000ms
        intervalFunction: exponential # Экспоненциальная задержка
        multiplier: 2
        retryExceptions:
#          - com.example.JWKSFetchException
          - org.springframework.web.client.ResourceAccessException
